# Do not change this unless required.
config-version = "2.6"

# Default IP, Port, MOTD and Max Players.
bind = "0.0.0.0:25565"
motd = "<b><gold>ViaTesting</gold> </b><blue>Testserver (Proxy)</blue>"
show-max-players = 20

# Connectivity configuration.
force-key-authentication = false
forwarding-secret-file = "forwarding.secret"
online-mode = true
player-info-forwarding-mode = "legacy"
prevent-client-proxy-connections = false

# Backend servers that velocity should pick up.
[servers]
lobby = "0.0.0.0:25566"
try = ["lobby"]

[forced-hosts]
"lobby.example.com" = ["lobby"]

# Query for Velocity, Disabled by default.
[query]
enabled = false
port = 25565