# Backend servers that Bungee should prioritize,
# Also controls the default IP, Port, MOTD and Max Players.
listeners:
- query_port: 25565
  host: 0.0.0.0:25565
  motd: '&6&lViaTesting&r &9Testserver (Proxy)'
  max_players: 20
  priorities:
  - lobby
  forced_hosts:
    lobby.example.com: lobby
  bind_local_address: true
  force_default_server: false
  query_enabled: false

# Backend servers that Bungee should pick up.
servers:
  lobby:
    motd: '&6&lViaTesting&r &9Testserver (Backend)'
    address: localhost:25566
    restricted: false

# Connectivity configuration.
enforce_secure_profile: false
ip_forward: true
online_mode: true
prevent_proxy_connections: false